# test pipeline to verify sccache functionality

name: $(Date:yyyy.MM.dd)$(Rev:r)

trigger:
- main

pr: none

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
- name: CCACHE_DIR
  value: $(Build.SourcesDirectory)/ccache
- group: sccache-vars

jobs:
- job: Build
  steps:
  - script: |
      echo $(CCACHE_DIR)
      echo $(blob_container)
      echo $(connection_string)