# test pipeline to verify sccache functionality

name: $(Date:yyyy.MM.dd)$(Rev:r)

trigger:
- main

pr: none

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
  CCACHE_DIR: $(Build.SourcesDirectory)/ccache

jobs:
- job: Build
  steps:
  - script: |
      echo 'OK'