# test pipeline to verify sccache functionality

name: $(Date:yyyy.MM.dd)$(Rev:r)

trigger:
- main

pr: none

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
- group: sccache-vars

jobs:
- job: Build
  container:
    image: docker.io/csauer42/cmake-builder
    endpoint: docker-hub-csauer42
  steps:
  - script: |
      export SCCACHE_AZURE_BLOB_CONTAINER="$(blob_container)"
      export SCCACHE_AZURE_CONNECTION_STRING="$(connection_string)"
  - task: CMake@1
    inputs:
      cmakeArgs: -DBENCHMARK_DOWNLOAD_DEPENDENCIES=on -DCMAKE_BUILD_TYPE=Release ../
  - task: CMake@1
    inputs:
      cmakeArgs: --build . --config Release
  - script: |
      sccache -s
