# test pipeline to verify sccache functionality

name: $(Date:yyyy.MM.dd)$(Rev:r)

trigger:
- main

pr: none

resources:
- repo: self

pool: local-builds

variables:
- group: sccache-vars

jobs:
- job: Build
  container:
    image: docker.io/csauer42/cmake-builder
    endpoint: docker-hub-csauer42
  steps:
  - task: CMake@1
    inputs:
      cmakeArgs: -DBENCHMARK_DOWNLOAD_DEPENDENCIES=on -DCMAKE_BUILD_TYPE=Release ../
  - task: CMake@1
    env:
      SCCACHE_AZURE_CONNECTION_STRING: $(sccache.azure.connection.string)
    inputs:
      cmakeArgs: --build . --config Release
  - script: |
      sccache --version
      sccache -s
